config/routes.rb
Rails.application.routes.draw do
  get 'students/new'
  get 'students/destroy'
  get 'students/index'
  get 'students/show'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "students#index"
  resources :students
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/mix.rb
class Mix < ApplicationRecord
  belongs_to :student
  belongs_to :project
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :mix
  has_many :students, through: :mix
end

app/models/student.rb
class Student < ApplicationRecord
	validates :name, presence: true, length: {minimum: 4, maximum: 20}
	validates :email, presence: true
	has_many :mix
	has_many :projects, through: :mix
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  # allow_browser versions: :modern
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def new
    @student = Student.new
  end

  def create
    @student = Student.new(params_require)
    if @student.save
      redirect_to @student 
    else
      render 'new'
    end 
  end

  def destroy
    @student = Student.find(params[:id])
    @student.delete
  end

  def index
    @students = Student.all
  end

  def show
    @student = Student.find(params[:id])
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])
    @student.update(params_require)
    if @student.save
      redirect_to @student
    else
      render 'new'
    end
  end


  private
  def params_require
    params.require(:student).permit(:name, :email)
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Tryapp1" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/destroy.html.erb
<h1>Students#destroy</h1>
<p>Find me in app/views/students/destroy.html.erb</p>

app/views/students/edit.html.erb
<div class="col-md-12">
	<div class="col-md-4 mx-auto">
    <%= form_with(model: @student, local: true) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control" %>
      <%= f.submit "edit", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/students/index.html.erb
<h1>Students#index</h1>
<p>Find me in app/views/students/index.html.erb</p>
<br>
<%= link_to "new ", new_student_path %>
<table>
	<thead>
		<th><strong>name</strong>
		<th><strong>email</strong>
		<th><strong>view</strong>
		<th><strong>edit</strong>
		<th><strong>delete</strong>
	</thead>
	<tbody>
		<% @students.each do |s| %>
      <strong><%= s.name %> </strong>
      <strong><%= s.email %> </strong>
      <%= link_to "view", student_path(s) %>
      <%= link_to "edit", edit_student_path(s) %>
      <%= button_to "delete", student_path(s), method: :delete %>
    <% end %>
	</tbody>
</table>

app/views/students/new.html.erb
<h1>Students#new</h1>
<p>Find me in app/views/students/new.html.erb</p>
<div class="col-md-12">
	<div class="col-md-4 mx-auto">
    <%= form_with(model: @student, local: true) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control" %>
      <%= f.submit "new", class: "btn btn-primary" %>
    <%end%>
  </div>
</div>

app/views/students/show.html.erb
<h1>Students#show</h1>
<p>Find me in app/views/students/show.html.erb</p>
<strong>Name: <%= @student.name %></strong>
<strong>Email: <%= @student.email %></strong>